version: '3'
services:
  laravel5.7-learn-larabbs:
    container_name: laravel5.7-learn-larabbs
    build: docker
    volumes:
      - $HOME:/root/.ssh
      - ./:/data/app/project/
    environment:
      TZ: Asia/Shanghai
    command: bash -c "/home/root/run.sh"
    ports:
      - "8899:80"
